# .github/workflows/main_pr.yml
name: CI for pull request to main branch

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  marker:
    name: Log branch workflow start
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Running main branch pull request workflow..."

  lint:
    uses: ./.github/workflows/_lint.yml

  lint_leptos:
    uses: ./.github/workflows/_lint_leptos.yml

  unit_and_integration_tests:
    uses: ./.github/workflows/_unit_and_integration_tests.yml
    with:
      features: "ssr"

  end_to_end_tests:
    uses: ./.github/workflows/_end_to_end_tests.yml
